runtime: nodejs
env: flex

network:
  session_affinity: true
vpc_access_connector:
#  name: 'projects/<PROJECT_ID>/locations/<REGION>/connectors/<CONNECTOR_NAME>'
  name: cafh

env_variables:

## You want to set up your variables like so:
#  REDIS_IP: ...
#  REDIS_PORT: .. 
